import { useEffect, useMemo, useRef, useState } from 'react'
import { Activity, ArrowDownToLine, ArrowUpRight, CalendarDays, CarFront, ChevronDown, CircleHelp, Database, FileUp, LayoutDashboard, Map, Moon, Search, Shield, SlidersHorizontal, Sun, Table2, Upload, UsersRound, X } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { demoRecords, districts } from '../data/demo'
import { comparePeriods, csvRows, downloadCsv, groupCount, groupValue, monthlySourceTrend, monthlyTrend } from '../services/statistics'
import type { CrimeRecord } from '../types'

const sources = [{ key: 'ROAD_POLICE', label: 'Дорожная полиция' }, { key: 'LOCAL_POLICE', label: 'Участковые' }, { key: 'AUTOMATED_SYSTEMS', label: 'Автоматические комплексы' }, { key: 'OTHER', label: 'Другие источники' }]
const fmt = (n: number) => new Intl.NumberFormat('ru-RU').format(n)
const monthName = (m: string) => new Date(`${m}-02`).toLocaleDateString('ru-RU', { month: 'long', year: 'numeric' })

export default function App() {
  const [records, setRecords] = useState<CrimeRecord[]>(() => {
    try { const saved = localStorage.getItem('aqmola-imported-records'); return saved ? [...demoRecords, ...JSON.parse(saved) as CrimeRecord[]] : demoRecords }
    catch { return demoRecords }
  })
  const [district, setDistrict] = useState('Все районы')
  const [source, setSource] = useState('Все источники')
  const [mapSource, setMapSource] = useState<CrimeRecord['source_type']>('ROAD_POLICE')
  const [mapIndicator, setMapIndicator] = useState('Количество ДТП')
  const [from, setFrom] = useState('2026-01')
  const [to, setTo] = useState('2026-12')
  const [search, setSearch] = useState('')
  const [dark, setDark] = useState(false)
  const [notice, setNotice] = useState('')
  const fileRef = useRef<HTMLInputElement>(null)
  useEffect(() => {
    try { localStorage.setItem('aqmola-imported-records', JSON.stringify(records.filter(r => !r.id.startsWith('demo-')))) }
    catch { setNotice('Не удалось сохранить импортированные данные в локальном хранилище браузера.') }
  }, [records])
  const filtered = useMemo(() => records.filter(r => r.date.slice(0,7) >= from && r.date.slice(0,7) <= to && (district === 'Все районы' || r.district === district) && (source === 'Все источники' || r.source_type === source)), [records, from, to, district, source])
  const tableRecords = useMemo(() => filtered.filter(r => !search || `${r.district} ${r.category} ${r.indicator}`.toLowerCase().includes(search.toLowerCase())), [filtered, search])
  const trend = useMemo(() => monthlyTrend(filtered), [filtered])
  const sourceTrend = useMemo(() => monthlySourceTrend(filtered, from, to), [filtered, from, to])
  const comparisonRecords = useMemo(() => records.filter(r => (district === 'Все районы' || r.district === district) && (source === 'Все источники' || r.source_type === source)), [records, district, source])
  const comparison = useMemo(() => comparePeriods(comparisonRecords, from, to), [comparisonRecords, from, to])
  const byDistrict = useMemo(() => groupCount(filtered, r => r.district).sort((a,b) => b.value-a.value), [filtered])
  const byCategory = useMemo(() => groupCount(filtered, r => r.category).sort((a,b) => b.value-a.value).slice(0,5), [filtered])
  const mapIndicators = useMemo(() => [...new Set(records.filter(r => r.source_type === mapSource && r.date.slice(0,7) >= from && r.date.slice(0,7) <= to).map(r => r.indicator))].sort(), [records, mapSource, from, to])
  const activeMapIndicator = mapIndicators.includes(mapIndicator) ? mapIndicator : mapIndicators[0] ?? ''
  const mapRows = useMemo(() => records.filter(r => r.date.slice(0,7) >= from && r.date.slice(0,7) <= to && r.source_type === mapSource && r.indicator === activeMapIndicator && (district === 'Все районы' || r.district === district)), [records, from, to, mapSource, activeMapIndicator, district])
  const mapValues = useMemo(() => groupValue(mapRows, r => r.district), [mapRows])
  const mapUnit = mapRows[0]?.unit ?? 'ед.'
  const road = filtered.filter(r => r.source_type === 'ROAD_POLICE').length
  const local = filtered.filter(r => r.source_type === 'LOCAL_POLICE').length
  const automated = filtered.filter(r => r.source_type === 'AUTOMATED_SYSTEMS').length
  const total = filtered.length
  const months = [...new Set(records.map(r => r.date.slice(0,7)))].sort()
  const prevMonth = (m: string) => { const d = new Date(`${m}-02`); d.setMonth(d.getMonth()-1); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}` }
  const previousValue = useMemo(() => { const m = prevMonth(to); return records.filter(r => r.date.slice(0,7) === m && (district === 'Все районы' || r.district === district) && (source === 'Все источники' || r.source_type === source)).length }, [records, to, district, source])
  const currValue = records.filter(r => r.date.slice(0,7) === to && (district === 'Все районы' || r.district === district) && (source === 'Все источники' || r.source_type === source)).length
  const change = previousValue ? ((currValue - previousValue) / previousValue) * 100 : 0
  const displayRows = tableRecords.slice().sort((a,b) => b.date.localeCompare(a.date)).slice(0, 10)
  const onImport = async (file?: File) => {
    if (!file) return
    try { const parsed = csvRows(await file.text()); const existing = new Set(records.map(r => `${r.date}|${r.district}|${r.source_type}|${r.category}|${r.indicator}`)); const fresh = parsed.filter(r => !existing.has(`${r.date}|${r.district}|${r.source_type}|${r.category}|${r.indicator}`)); setRecords(prev => [...prev, ...fresh]); setNotice(`Импортировано строк: ${fresh.length}. Повторов пропущено: ${parsed.length-fresh.length}.`)
    } catch (e) { setNotice(e instanceof Error ? e.message : 'Не удалось прочитать CSV.') }
    if (fileRef.current) fileRef.current.value = ''
  }
  const activeRange = months.length ? `${monthName(from)} — ${monthName(to)}` : ''
  return <div className={dark ? 'app dark' : 'app'}>
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark"><Shield size={19}/></div><div><b>AQMOLA</b><small>CRIME MONITOR</small></div></div>
      <div className="workspace"><div className="workspace-icon"><Map size={17}/></div><div><b>Акмолинская область</b><small>Аналитическая панель</small></div><ChevronDown size={15}/></div>
      <div className="nav-label">РАБОЧАЯ ОБЛАСТЬ</div>
      <button className="nav-item selected"><LayoutDashboard size={17}/>Обзор</button><button className="nav-item" onClick={()=>document.getElementById('analytics')?.scrollIntoView({behavior:'smooth'})}><Activity size={17}/>Аналитика</button><button className="nav-item" onClick={()=>document.getElementById('records')?.scrollIntoView({behavior:'smooth'})}><Table2 size={17}/>Правонарушения</button><button className="nav-item" onClick={()=>document.getElementById('map-section')?.scrollIntoView({behavior:'smooth'})}><Map size={17}/>География</button>
      <div className="nav-label sources-title">ИСТОЧНИКИ ДАННЫХ <span>03</span></div>
      {sources.slice(0,3).map(s=><button key={s.key} className="source-nav" onClick={()=>setSource(source===s.key?'Все источники':s.key)}><i className={`source-dot ${s.key.toLowerCase()}`}/>{s.label}<span className="tiny-check">{source===s.key?'✓':''}</span></button>)}
      <div className="sidebar-bottom"><div className="demo-badge"><span className="demo-pulse"/>ДЕМО-РЕЖИМ<small>Синтетические данные</small></div><div className="profile"><div className="avatar">А</div><div><b>Аналитик</b><small>Локальная сессия</small></div><ChevronDown size={15}/></div></div>
    </aside>
    <main className="main">
      <header className="topbar"><div className="breadcrumbs">Рабочая область <span>/</span> <b>Обзор</b></div><div className="top-actions"><span className="updated"><i/>Обновлено только что</span><button className="icon-btn" title="Сменить тему" onClick={()=>setDark(!dark)}>{dark?<Sun size={17}/>:<Moon size={17}/>}</button><button className="icon-btn help" title="Информация о панели"><CircleHelp size={17}/></button><div className="top-avatar">А</div></div></header>
      <div className="content">
        <div className="title-row"><div><div className="eyebrow"><span className="live-dot"/> МОНИТОРИНГ ОБСТАНОВКИ <span className="eyebrow-divider">/</span> 2026</div><h1>Обзор правонарушений</h1><p className="subtitle">Агрегированная статистика по районам Акмолинской области</p></div><div className="title-actions"><button className="btn outline" onClick={()=>fileRef.current?.click()}><Upload size={16}/>Импорт CSV</button><input ref={fileRef} type="file" accept=".csv,text/csv" hidden onChange={e=>onImport(e.target.files?.[0])}/><button className="btn primary" onClick={()=>downloadCsv(filtered)}><ArrowDownToLine size={16}/>Экспорт данных</button></div></div>
        <div className="demo-banner"><div className="banner-icon"><Database size={17}/></div><div><b>Демонстрационные данные</b><span>Не являются официальной статистикой. Используются только для показа возможностей панели.</span></div><button aria-label="Скрыть уведомление" onClick={e=>(e.currentTarget.parentElement as HTMLElement).remove()}><X size={16}/></button></div>
        <section className="filters"><div className="filter-heading"><SlidersHorizontal size={15}/><b>Фильтры</b><span>Настройте параметры выборки</span></div><div className="filter-controls"><label className="filter"><span>ПЕРИОД</span><div><CalendarDays size={15}/><select value={from} onChange={e=>setFrom(e.target.value)}>{months.map(m=><option key={m} value={m}>{monthName(m)}</option>)}</select><span className="range-sep">—</span><select value={to} onChange={e=>setTo(e.target.value)}>{months.map(m=><option key={m} value={m}>{monthName(m)}</option>)}</select></div></label><label className="filter"><span>РАЙОН</span><div><Map size={15}/><select value={district} onChange={e=>setDistrict(e.target.value)}><option>Все районы</option>{districts.map(d=><option key={d}>{d}</option>)}</select></div></label><label className="filter"><span>ИСТОЧНИК</span><div><Database size={15}/><select value={source} onChange={e=>setSource(e.target.value)}><option>Все источники</option>{sources.map(s=><option key={s.key} value={s.key}>{s.label}</option>)}</select></div></label><button className="clear-filter" onClick={()=>{setFrom(months[0]||'2026-01');setTo(months[months.length-1]||'2026-12');setDistrict('Все районы');setSource('Все источники');setSearch('')}}>Сбросить</button></div></section>
        <div className="period-note"><span>ПОКАЗАНЫ ДАННЫЕ ЗА</span><b>{activeRange}</b><i/> <span>ВСЕ ИСТОЧНИКИ</span><b>{source==='Все источники'?'':sources.find(s=>s.key===source)?.label}</b></div>
        <section className="kpis"><Kpi title="Агрегированных записей" value={total} unit="строк в выборке" icon={<Shield size={17}/>} color="blue" change={previousValue ? change : undefined}/><Kpi title="Дорожная полиция" value={road} unit="строк данных" icon={<CarFront size={17}/>} color="violet" source="ROAD_POLICE" onSource={setSource}/><Kpi title="Участковые инспекторы" value={local} unit="строк данных" icon={<UsersRound size={17}/>} color="green" source="LOCAL_POLICE" onSource={setSource}/><Kpi title="Автоматические системы" value={automated} unit="строк данных" icon={<Activity size={17}/>} color="amber" source="AUTOMATED_SYSTEMS" onSource={setSource}/></section>
        <section className="charts-grid"><article className="panel trend-panel"><div className="panel-heading"><div><h2>Динамика набора данных</h2><p>Число агрегированных записей по месяцам · {activeRange}</p></div><button className="more-btn" aria-label="Дополнительные параметры">•••</button></div><div className="chart-legend"><span><i className="legend-line"/>Все источники</span><span className="chart-total">Записей <b>{fmt(total)}</b></span></div><div className="line-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={trend} margin={{top:10,right:12,left:-16,bottom:0}}><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="var(--grid)"/><XAxis dataKey="month" tickLine={false} axisLine={false} tick={{fill:'var(--muted)',fontSize:11}}/><YAxis tickLine={false} axisLine={false} tick={{fill:'var(--muted)',fontSize:11}}/><Tooltip formatter={(v)=>[fmt(Number(v)),'Записей']} contentStyle={{borderRadius:10,border:'1px solid var(--border)',background:'var(--surface)',fontSize:12}}/><Line type="monotone" dataKey="value" stroke="#5968e8" strokeWidth={2.5} dot={{r:3,fill:'#5968e8',strokeWidth:2,stroke:'var(--surface)'}} activeDot={{r:5}}/></LineChart></ResponsiveContainer></div><div className="chart-foot"><span><CalendarDays size={13}/>Количество строк по месяцам</span><span>Источник: все подключённые</span></div></article>
          <article className="panel district-panel"><div className="panel-heading"><div><h2>Данные по районам</h2><p>Число агрегированных записей</p></div><button className="text-link" onClick={()=>document.getElementById('records')?.scrollIntoView({behavior:'smooth'})}>Подробнее <ArrowUpRight size={13}/></button></div><div className="bar-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={byDistrict.slice(0,6)} layout="vertical" margin={{top:2,right:18,left:0,bottom:0}}><CartesianGrid strokeDasharray="3 5" horizontal={false} stroke="var(--grid)"/><XAxis type="number" hide/><YAxis type="category" dataKey="name" width={119} tickLine={false} axisLine={false} tick={{fill:'var(--muted)',fontSize:10}}/><Tooltip formatter={(v)=>[fmt(Number(v)),'Записей']} cursor={{fill:'var(--hover)'}} contentStyle={{borderRadius:10,border:'1px solid var(--border)',background:'var(--surface)',fontSize:12}}/><Bar dataKey="value" fill="#7582ec" radius={[0,5,5,0]} barSize={17}/></BarChart></ResponsiveContainer></div><div className="chart-foot"><span>Районов в выборке <b>{byDistrict.length}</b></span><span>Число строк данных</span></div></article></section>
        <section className="analytics-grid" id="analytics"><article className="panel source-trend-panel"><div className="panel-heading"><div><h2>Динамика по источникам</h2><p>Количество агрегированных записей в месяц · {activeRange}</p></div><span className="soft-count">{source==='Все источники'?'Все источники':sources.find(s=>s.key===source)?.label}</span></div><div className="source-line-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={sourceTrend} margin={{top:8,right:9,left:-17,bottom:0}}><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="var(--grid)"/><XAxis dataKey="month" tickLine={false} axisLine={false} tick={{fill:'var(--muted)',fontSize:10}}/><YAxis tickLine={false} axisLine={false} tick={{fill:'var(--muted)',fontSize:10}}/><Tooltip formatter={(v)=>[fmt(Number(v)),'Записей']} contentStyle={{borderRadius:10,border:'1px solid var(--border)',background:'var(--surface)',fontSize:11}}/><Legend iconType="circle" iconSize={7} wrapperStyle={{fontSize:9,color:'var(--muted)'}}/><Line name="Дорожная полиция" type="monotone" dataKey="ROAD_POLICE" stroke="#6876e5" strokeWidth={2} dot={false}/><Line name="Участковые" type="monotone" dataKey="LOCAL_POLICE" stroke="#4ba783" strokeWidth={2} dot={false}/><Line name="Автоматические системы" type="monotone" dataKey="AUTOMATED_SYSTEMS" stroke="#df9d4e" strokeWidth={2} dot={false}/><Line name="Другие источники" type="monotone" dataKey="OTHER" stroke="#9b78ce" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div><div className="chart-foot"><span>Источники показаны отдельными рядами</span><span>Число записей, не число событий</span></div></article>
          <article className="panel comparison-panel"><div className="panel-heading"><div><h2>Сравнение периодов</h2><p>Выбранный интервал и такой же интервал до него</p></div><span className="compare-icon"><Activity size={15}/></span></div><div className="compare-periods"><div><span>ТЕКУЩИЙ</span><b>{monthName(from)} — {monthName(to)}</b><strong>{fmt(comparison.currentTotal)} <small>записей</small></strong></div><span className="compare-arrow">↔</span><div><span>ПРЕДЫДУЩИЙ</span><b>{monthName(comparison.previousFrom)} — {monthName(comparison.previousTo)}</b><strong>{fmt(comparison.previousTotal)} <small>записей</small></strong></div></div><div className="comparison-total"><span>Изменение числа записей</span><b className={comparison.totalChange!==null&&comparison.totalChange<0?'down':''}>{comparison.totalChange===null?'Нет базы для сравнения':`${comparison.totalChange>0?'+':''}${comparison.totalChange.toFixed(1)}%`}</b></div><div className="compare-table"><div className="compare-table-head"><span>ИСТОЧНИК</span><span>ТЕКУЩИЙ</span><span>ПРЕДЫДУЩИЙ</span><span>ИЗМЕНЕНИЕ</span></div>{comparison.rows.filter(row=>(source==='Все источники'||row.source===source)&&(row.current>0||row.previous>0)).map(row=><div className="compare-row" key={row.source}><span><i className={`source-dot ${row.source.toLowerCase()}`}/>{row.label}</span><b>{fmt(row.current)}</b><b>{fmt(row.previous)}</b><strong className={row.change!==null&&row.change<0?'down':''}>{row.change===null?'—':`${row.change>0?'+':''}${row.change.toFixed(1)}%`}</strong></div>)}</div><div className="card-caption">Процент показывает изменение количества строк; причина изменения по имеющимся данным не установлена.</div></article></section>
        <section className="lower-grid"><article className="panel categories-panel"><div className="panel-heading"><div><h2>Категории правонарушений</h2><p>Распределение по типам в выборке</p></div><span className="soft-count">{byCategory.length} категорий</span></div><div className="category-list">{byCategory.map((c,i)=><div className="category-row" key={c.name}><span className={`category-icon cat-${i}`}><Activity size={15}/></span><div className="category-info"><b>{c.name}</b><div className="progress"><i style={{width:`${Math.max(8,c.value/(byCategory[0]?.value||1)*100)}%`}}/></div></div><strong>{fmt(c.value)}</strong><span className="category-percent">{total?Math.round(c.value/total*100):0}%</span></div>)}</div><div className="card-caption">Значения разных показателей могут иметь разные единицы измерения.</div></article>
          <article className="panel map-panel" id="map-section"><div className="panel-heading"><div><h2>География данных</h2><p>Красная зона: больше 100 {mapUnit} за выбранный период</p></div><button className="map-expand" title="Схема, не географическая карта"><Map size={15}/></button></div><div className="map-filters"><label><span>ИСТОЧНИК</span><select value={mapSource} onChange={e=>setMapSource(e.target.value as CrimeRecord['source_type'])}>{sources.map(item=><option key={item.key} value={item.key}>{item.label}</option>)}</select></label><label><span>ПОКАЗАТЕЛЬ</span><select value={activeMapIndicator} onChange={e=>setMapIndicator(e.target.value)}>{mapIndicators.map(item=><option key={item}>{item}</option>)}</select></label><b className="threshold-tag">Порог &gt; 100</b></div><div className="map-content"><div className="schematic-map"><div className="map-label">СХЕМА РАЙОНОВ · {activeMapIndicator}</div><div className="district-tiles">{districts.map((d,i)=>{const value=mapValues.find(x=>x.name===d)?.value??0;const over=value>100;return <button className={`district-tile tile-${i} ${over?'over-threshold':''} ${district===d?'active':''}`} key={d} onClick={()=>setDistrict(district===d?'Все районы':d)}><span>{d.replace(' район','').replace('г. ','')}</span><b>{fmt(value)}</b></button>})}</div><span className="map-watermark">AQMOLA REGION</span></div><div className="map-legend"><span><i className="shade low"/>≤ 100</span><span><i className="shade high"/> &gt; 100</span></div></div><div className="map-note"><CircleHelp size={13}/>Схематическое представление. Значение суммирует только выбранный показатель и источник.</div></article></section>
        <section className="panel records-panel" id="records"><div className="panel-heading records-head"><div><h2>Последние записи</h2><p>Агрегированные данные по выбранным фильтрам</p></div><div className="records-actions"><div className="searchbox"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Поиск по таблице"/></div><button className="btn small outline" onClick={()=>downloadCsv(filtered)}><ArrowDownToLine size={14}/>CSV</button></div></div><div className="table-wrap"><table><thead><tr><th>ДАТА</th><th>РАЙОН</th><th>ИСТОЧНИК</th><th>КАТЕГОРИЯ</th><th>ПОКАЗАТЕЛЬ</th><th>ЗНАЧЕНИЕ</th><th>СТАТУС</th></tr></thead><tbody>{displayRows.map(r=><tr key={r.id}><td>{new Date(`${r.date}T00:00:00`).toLocaleDateString('ru-RU',{day:'2-digit',month:'short',year:'numeric'})}</td><td className="td-district">{r.district}</td><td><span className="source-cell"><i className={`source-dot ${r.source_type.toLowerCase()}`}/>{r.source_name}</span></td><td>{r.category}</td><td>{r.indicator}</td><td className="td-value">{fmt(r.value)} <small>{r.unit}</small></td><td><span className={`status-pill ${r.data_status==='demo'?'demo':'official'}`}>{r.data_status==='demo'?'Демо':'Импорт'}</span></td></tr>)}</tbody></table>{!displayRows.length&&<div className="empty-state">По выбранным фильтрам записей нет.</div>}</div><div className="table-footer"><span>Показано <b>{displayRows.length}</b> из <b>{fmt(tableRecords.length)}</b> записей</span><button onClick={()=>downloadCsv(filtered)}>Скачать все данные <ArrowDownToLine size={14}/></button></div></section>
        <footer className="footer"><span>© 2026 Aqmola Crime Monitor</span><span><i className="footer-dot"/>Демонстрационный набор данных <span className="footer-sep">·</span> Не является официальной статистикой</span><button title="Информация"><CircleHelp size={15}/></button></footer>
      </div>
    </main>
    {notice&&<div className="toast"><FileUp size={17}/><span>{notice}</span><button onClick={()=>setNotice('')}><X size={15}/></button></div>}
  </div>
}

function Kpi({title,value,unit,icon,color,change,source,onSource}: {title:string;value:number;unit:string;icon:React.ReactNode;color:string;change?:number;source?:string;onSource?:(source:string)=>void}) {
  return <article className="kpi"><div className={`kpi-icon ${color}`}>{icon}</div><span className="kpi-label">{title}</span><strong className="kpi-value">{fmt(value)}</strong><div className="kpi-bottom"><span>{unit}</span>{source?<button onClick={()=>onSource?.(source)} className="kpi-source">Смотреть <ArrowUpRight size={12}/></button>:change!==undefined?<span className={`change ${change<0?'down':''}`}><ArrowUpRight size={12}/>{change>0?'+':''}{change.toFixed(1)}% к пред. месяцу</span>:null}</div></article>
}
